### ISSUE TITLE
Since January 1st 2020, ChronosVenger does not present any events

### ISSUE THREAD

**Issue by Lyro1** [igormages/ChronosVenger#2]
Since January 1st 2020, ChronosVenger does not present any events.
I am not sure it has something to do with the date, but no event shows up at all.
It does not seems to be related to Chronos, because iChronos is still working.

**Comment by igormages** [comment]
C'est drôle, comme on a écrit le site en anglais vous écrivez ici en anglais haha.
Le soucis c'est que je veux bien corriger le code (que j'ai fait il y a 6 ans déjà !), mais je n'ai plus accès aux serveurs... enfin je crois ?

**Comment by igormages** [comment]
@T4ze comment ça fonctionne aujourd'hui ChronosVenger ? Vous pouvez me mettre au jus ?

**Comment by T4ze** [comment]
@Lyro1  Désole pour le délais de réponse,
C'est https://github.com/thibzr qui a reprise le projet pour intégrer quelques nouvelles fonctionnalités. A priori le problème avait été remonté et corrigé mais si il y a toujours des soucis, n'hésite pas à le contacter.

**Comment by igormages** [comment]
@T4ze le projet n'est plus en open source ? :'(
